version: '3.0'

services:
  postgres:
    container_name: db-postgres
    hostname: db-postgres
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: "PW@234"
      POSTGRES_USER: "pguser"
      POSTGRES_DB: "pgdb"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  pgadmin4:
    container_name: pgadmin4
    hostname: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@postgres"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin4@234"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge